# Generated by Django 5.1 on 2024-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_is_verified_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("subscribe", models.BooleanField(default=False)),
            ],
        ),
    ]
