# Generated by Django 5.1 on 2024-09-01 11:45

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0002_postgisgeometrycolumns_postgisspatialrefsys_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layer",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
