# Generated by Django 5.1 on 2024-09-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0004_project_projectlayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
