# Generated by Django 5.1 on 2024-09-12 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0006_alter_project_extent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="name",
        ),
    ]
