# Generated by Django 5.1 on 2024-09-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0008_directory_layer_directory_projectlayergroup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="key",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="property",
            name="feature",
        ),
        migrations.RemoveField(
            model_name="property",
            name="value",
        ),
        migrations.AddField(
            model_name="projectlayer",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_layers",
                to="gis.projectlayergroup",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="layer",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="gis.layer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("integer", "Integer"),
                    ("float", "Float"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("datetime", "DateTime"),
                    ("category", "Category"),
                    ("json", "JSON"),
                ],
                default="string",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "allowed_categories",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of allowed categories for 'category' type",
                        null=True,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="gis.feature",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="gis.property",
                    ),
                ),
            ],
        ),
    ]
