# Generated by Django 5.1 on 2024-09-19 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0011_alter_layer_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="layer",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="layer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("directory__isnull", True)),
                fields=("name", "user"),
                name="unique_name_user_when_directory_is_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="layer",
            constraint=models.UniqueConstraint(
                fields=("name", "user", "directory"), name="unique_name_user_directory"
            ),
        ),
    ]
