# Generated by Django 5.1 on 2024-09-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0012_alter_layer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerfeature",
            name="properties",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="FeaturePropertyValue",
        ),
    ]
