# Generated by Django 5.1 on 2024-09-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0013_layerfeature_properties_delete_featurepropertyvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlayer",
            name="basemap",
            field=models.CharField(
                blank=True,
                choices=[("osm", "OpenStreetMap"), ("satellite", "Satellite")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectlayer",
            name="layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_layers",
                to="gis.layer",
            ),
        ),
    ]
