# Generated by Django 5.1 on 2024-09-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0014_projectlayer_basemap_alter_projectlayer_layer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectlayer",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="projectlayer",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
