# Generated by Django 5.1 on 2024-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0015_alter_projectlayer_options_projectlayer_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlayer",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
