name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

    - name: Deploy via SSH
      run: |
        ssh root@${{ screts.DIGITALOCEAN_IP }} << 'EOF'
          cd /var/www/spatial-lab/spatiallab/docker-compose
          git pull origin main
          docker-compose pull
          docker-compose up -d
          docker system prune -f
        EOF