name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker to GCP
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/django-app ./django
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app ./react
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/django-app
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app

    - name: Deploy Django to Cloud Run
      run: |
        gcloud run deploy django-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/django-app:latest \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 512Mi
          --add-cloudsql-instances ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy React to Cloud Run
      run: |
        gcloud run deploy react-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app:latest \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 512Mi
